In [1]:
# Initial imports.
import sqlalchemy
import numpy as np
from pathlib import Path
from collections import Counter
import pandas as pd
from path import Path
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sqlalchemy import create_engine

In [ ]:
# Connect to Google Big Query to access cloud database

# from google.colab import auth
# auth.authenticate_user()

# from google.cloud import bigquery

# # https://cloud.google.com/resource-manager/docs/creating-managing-projects
# project_id = 'restaurant-scores-345323'
# client = bigquery.Client(project=project_id)

# restaurant_data_array = [] 

# for dataset in client.list_datasets():
#   print(dataset.dataset_id)
#   restaurant_data_array.append(dataset)

# %load_ext google.colab.data_table
# import pandas as pd

# df = pd.DataFrame(restaurant_data_array)

In [2]:
# Loading data
file_path = Path("../Data/final_table_ml_stage2.csv")
risk_df = pd.read_csv(file_path)
risk_df.head()

,business_postal_code_1,inspection_id,inspection_date,inspection_score,violation_description,risk_category,neighborhoods,Current Police Districts,population,avg_income
0,94133,835_20180917,September,88,Improper food storage,Low Risk,107,6,26827.0,40990.0
1,94108,905_20190415,April,87,High risk vermin infestation,High Risk,19,6,13716.0,31542.0
2,94118,1203_20170803,August,77,Moderate risk food holding temperature,Moderate Risk,5,8,38939.0,61609.0
3,94109,1345_20170928,September,81,Improper cooling methods,High Risk,105,4,56322.0,43444.0
4,94114,1352_20180620,June,74,Non service animal,Low Risk,38,3,30574.0,75727.0

In [3]:
# Drop inspection_id
risk_df1 = risk_df.drop(columns='inspection_id')

In [4]:
#drop inspection_score
risk_df2 = risk_df1.drop(columns='inspection_score')
risk_df2

,business_postal_code_1,inspection_date,violation_description,risk_category,neighborhoods,Current Police Districts,population,avg_income
0,94133,September,Improper food storage,Low Risk,107,6,26827.0,40990.0
1,94108,April,High risk vermin infestation,High Risk,19,6,13716.0,31542.0
2,94118,August,Moderate risk food holding temperature,Moderate Risk,5,8,38939.0,61609.0
3,94109,September,Improper cooling methods,High Risk,105,4,56322.0,43444.0
4,94114,June,Non service animal,Low Risk,38,3,30574.0,75727.0
...,...,...,...,...,...,...,...,...
20239,94118,October,Improper storage of equipment utensils or linens,Low Risk,5,8,38939.0,61609.0
20240,94112,April,Moderate risk food holding temperature,Moderate Risk,90,9,73104.0,57629.0
20241,94103,July,Inadequate warewashing facilities or equipment,Low Risk,53,3,23016.0,31131.0
20242,94103,January,Improper cooling methods,High Risk,32,1,23016.0,31131.0
20243,94102,May,Inadequate and inaccessible handwashing facili...,Moderate Risk,21,4,28991.0,22351.0

In [5]:
# Create our features
X = risk_df2.drop(columns='risk_category')

# Create our target
y = risk_df2['risk_category']
y.value_counts()

Low Risk         9820
Moderate Risk    7599
High Risk        2825
Name: risk_category, dtype: int64

In [6]:
X.describe()

,business_postal_code_1,neighborhoods,Current Police Districts,population,avg_income
count,20244.000000,20244.000000,20244.000000,20244.000000,20244.000000
mean,94114.061203,57.263485,5.399081,37738.252420,51372.542482
std,9.350442,35.014539,2.681820,21784.166592,17502.372234
min,94102.000000,1.000000,1.000000,374.000000,14609.000000
25%,94108.000000,28.000000,3.000000,23016.000000,40990.000000
50%,94111.000000,53.000000,6.000000,33115.000000,53795.000000
75%,94121.000000,96.000000,8.000000,55492.000000,61362.000000
max,94134.000000,117.000000,10.000000,74633.000000,95313.000000

In [7]:
# encode Month as a number
months_num = {
   "January": 1,
   "February": 2,
   "March": 3,
   "April": 4,
   "May": 5,
   "June": 6,
   "July": 7,
   "August": 8,
   "September": 9,
   "October": 10,
   "November": 11,
   "December": 12,
}

In [8]:
X["months_num"] = X["inspection_date"].apply(lambda x: months_num[x])

In [9]:
months_num["June"]

6

In [10]:
X

,business_postal_code_1,inspection_date,violation_description,neighborhoods,Current Police Districts,population,avg_income,months_num
0,94133,September,Improper food storage,107,6,26827.0,40990.0,9
1,94108,April,High risk vermin infestation,19,6,13716.0,31542.0,4
2,94118,August,Moderate risk food holding temperature,5,8,38939.0,61609.0,8
3,94109,September,Improper cooling methods,105,4,56322.0,43444.0,9
4,94114,June,Non service animal,38,3,30574.0,75727.0,6
...,...,...,...,...,...,...,...,...
20239,94118,October,Improper storage of equipment utensils or linens,5,8,38939.0,61609.0,10
20240,94112,April,Moderate risk food holding temperature,90,9,73104.0,57629.0,4
20241,94103,July,Inadequate warewashing facilities or equipment,53,3,23016.0,31131.0,7
20242,94103,January,Improper cooling methods,32,1,23016.0,31131.0,1
20243,94102,May,Inadequate and inaccessible handwashing facili...,21,4,28991.0,22351.0,5

In [11]:
# drop inspection_date
X = X.drop(columns='inspection_date')
X.head()

,business_postal_code_1,violation_description,neighborhoods,Current Police Districts,population,avg_income,months_num
0,94133,Improper food storage,107,6,26827.0,40990.0,9
1,94108,High risk vermin infestation,19,6,13716.0,31542.0,4
2,94118,Moderate risk food holding temperature,5,8,38939.0,61609.0,8
3,94109,Improper cooling methods,105,4,56322.0,43444.0,9
4,94114,Non service animal,38,3,30574.0,75727.0,6

In [12]:
# encode features
X_encoded = pd.get_dummies(X)
X_encoded

,business_postal_code_1,neighborhoods,Current Police Districts,population,avg_income,months_num,violation_description_Consumer advisory not provided for raw or undercooked foods,violation_description_Contaminated or adulterated food,violation_description_Discharge from employee nose mouth or eye,violation_description_Employee eating or smoking,...,violation_description_Unauthorized or unsafe use of time as a public health control measure,violation_description_Unclean hands or improper use of gloves,violation_description_Unclean nonfood contact surfaces,violation_description_Unclean or degraded floors walls or ceilings,violation_description_Unclean or unsanitary food contact surfaces,violation_description_Unclean unmaintained or improperly constructed toilet facilities,violation_description_Unpermitted food facility,violation_description_Unsanitary employee garments hair or nails,violation_description_Wiping cloths not clean or properly stored or inadequate sanitizer,violation_description_Worker safety hazards
0,94133,107,6,26827.0,40990.0,9,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,94108,19,6,13716.0,31542.0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,94118,5,8,38939.0,61609.0,8,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,94109,105,4,56322.0,43444.0,9,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,94114,38,3,30574.0,75727.0,6,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20239,94118,5,8,38939.0,61609.0,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20240,94112,90,9,73104.0,57629.0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20241,94103,53,3,23016.0,31131.0,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20242,94103,32,1,23016.0,31131.0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20243,94102,21,4,28991.0,22351.0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
# scale features
data_scaler = StandardScaler()

In [14]:
# fit transform 
X_encoded_scaled = data_scaler.fit_transform(X_encoded)
X_encoded_scaled[:1]

array([[ 2.02549393,  1.42048832,  0.22407683, -0.50089233, -0.59322238,
         0.76038594, -0.01721836, -0.06057074, -0.0070285 , -0.0722064 ,
        -0.04667138, -0.17506744, -0.23129437, -0.20204609, -0.15129174,
        -0.01405804, -0.14466839, -0.05719169,  4.92360592, -0.14106823,
        -0.0521944 , -0.15299117, -0.11045361, -0.13682034, -0.00994004,
        -0.01859842, -0.25024265, -0.08726597, -0.14573248, -0.04925792,
        -0.05675536, -0.04504888, -0.10625365, -0.0952464 , -0.27507124,
        -0.14643794, -0.18155591, -0.00994004, -0.01217432, -0.26506923,
        -0.22445793, -0.05452203, -0.03065015, -0.01571775, -0.08464147,
        -0.02534913, -0.00994004, -0.06569717, -0.04772267, -0.02331665,
        -0.0660753 , -0.03978967, -0.13205989, -0.01405804, -0.02108966,
        -0.02723068, -0.01859842, -0.28552724, -0.02435405, -0.12470493,
        -0.21037762, -0.32388457, -0.17759899, -0.07081065, -0.03445205,
        -0.02723068, -0.21444189, -0.02812442]])

In [15]:
# separate features and target into train and test using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded_scaled, y, random_state = 1)

In [16]:
y_train.value_counts()

Low Risk         7323
Moderate Risk    5724
High Risk        2136
Name: risk_category, dtype: int64

In [17]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [19]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [20]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [21]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1", "Actual 3"], columns=["Predicted 0", "Predicted 1", "Predicted 3"])

cm_df

          Predicted 0  Predicted 1  Predicted 3
Actual 0          689            0            0
Actual 1            0         2497            0
Actual 3            0            4         1871

In [22]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [23]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1  Predicted 3
Actual 0          689            0            0
Actual 1            0         2497            0
Actual 3            0            4         1871

Accuracy Score : 0.9992096423631693
Classification Report
               precision    recall  f1-score   support

    High Risk       1.00      1.00      1.00       689
     Low Risk       1.00      1.00      1.00      2497
Moderate Risk       1.00      1.00      1.00      1875

     accuracy                           1.00      5061
    macro avg       1.00      1.00      1.00      5061
 weighted avg       1.00      1.00      1.00      5061

In [24]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([6.08356680e-04, 1.00627039e-03, 6.83421967e-04, 5.18561241e-04,
       5.02038561e-04, 1.10330857e-03, 2.77574260e-04, 7.81680503e-03,
       0.00000000e+00, 8.81538921e-03, 4.08955523e-03, 1.01393168e-02,
       6.82635684e-02, 7.62144147e-02, 4.65536683e-02, 3.08274034e-04,
       4.17147868e-02, 1.01510448e-03, 1.59157944e-02, 7.18013451e-03,
       6.75635860e-03, 7.57949774e-03, 4.38276952e-03, 3.11200321e-02,
       1.02659395e-05, 3.83560804e-05, 7.35807927e-02, 2.30461840e-03,
       3.23626951e-02, 7.51072304e-04, 6.66814362e-03, 4.75734316e-03,
       3.78025146e-03, 3.52419617e-03, 8.64475119e-02, 3.35931251e-02,
       1.14753635e-02, 3.06003840e-04, 4.32059513e-04, 8.21208556e-02,
       6.75363644e-02, 5.89154128e-03, 2.71216156e-04, 9.69770607e-05,
       2.41014043e-03, 1.81890066e-04, 3.10540649e-04, 9.70241746e-03,
       4.84822659e-03, 1.27788549e-03, 1.21055457e-03, 2.59996067e-03,
       5.82576040e-03, 5.33886092e-04, 1.09083890e-03, 2.16060927e-04,
       9.71806985e-04, 3.50468189e-02, 1.75163705e-03, 3.02055620e-02,
       1.70225050e-02, 4.75553486e-02, 5.92733908e-02, 1.52296148e-03,
       3.24819794e-04, 2.38471235e-04, 1.71190911e-02, 2.45670128e-04])

In [25]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X_encoded.columns), reverse=True)

[(0.08644751194066674,
  'violation_description_Inadequately cleaned or sanitized food contact surfaces'),
 (0.08212085560346305,
  'violation_description_Moderate risk food holding temperature'),
 (0.07621441470908236,
  'violation_description_High risk food holding temperature'),
 (0.07358079265779606,
  'violation_description_Inadequate and inaccessible handwashing facilities'),
 (0.06826356835360052,
  'violation_description_Foods not protected from contamination'),
 (0.06753636439411607,
  'violation_description_Moderate risk vermin infestation'),
 (0.05927339076686733,
  'violation_description_Unclean or unsanitary food contact surfaces'),
 (0.04755534859694511,
  'violation_description_Unclean or degraded floors walls or ceilings'),
 (0.04655366828941554, 'violation_description_High risk vermin infestation'),
 (0.04171478680473679, 'violation_description_Improper cooling methods'),
 (0.03504681893895401,
  'violation_description_Unapproved or unmaintained equipment or utensils'),
 (0.03359312506454263,
  'violation_description_Insufficient hot water or running water'),
 (0.032362695108752434,
  'violation_description_Inadequate food safety knowledge or lack of certified food safety manager'),
 (0.031120032119491197, 'violation_description_Improper thawing methods'),
 (0.030205561997156294,
  'violation_description_Unclean hands or improper use of gloves'),
 (0.01711909106687004,
  'violation_description_Wiping cloths not clean or properly stored or inadequate sanitizer'),
 (0.017022504958120833,
  'violation_description_Unclean nonfood contact surfaces'),
 (0.015915794383121108, 'violation_description_Improper food storage'),
 (0.011475363530638704, 'violation_description_Low risk vermin infestation'),
 (0.010139316790876944,
  'violation_description_Food safety certificate or food handler card not available'),
 (0.009702417456244665,
  'violation_description_Noncompliance with HAACP plan or variance'),
 (0.008815389205095652, 'violation_description_Employee eating or smoking'),
 (0.007816805031936226,
  'violation_description_Contaminated or adulterated food'),
 (0.00757949774428239,
  'violation_description_Improper storage of equipment utensils or linens'),
 (0.0071801345132275545,
  'violation_description_Improper or defective plumbing'),
 (0.006756358599301884, 'violation_description_Improper reheating of food'),
 (0.006668143619827874,
  'violation_description_Inadequate procedures or records for time as a public health control'),
 (0.005891541284968012, 'violation_description_No hot water or running water'),
 (0.005825760403815296,
  'violation_description_Permit license or inspection report not posted'),
 (0.004848226587963067,
  'violation_description_Noncompliance with shell fish tags or display'),
 (0.004757343157784085,
  'violation_description_Inadequate sewage or wastewater disposal'),
 (0.0043827695196631995,
  'violation_description_Improper storage use or identification of toxic substances'),
 (0.00408955522881273, 'violation_description_Food in poor condition'),
 (0.003780251461787165,
  'violation_description_Inadequate ventilation or lighting'),
 (0.0035241961661923306,
  'violation_description_Inadequate warewashing facilities or equipment'),
 (0.002599960671251373, 'violation_description_Other moderate risk violation'),
 (0.00241014042513942,
  'violation_description_No thermometers or uncalibrated thermometers'),
 (0.002304618403752523,
  'violation_description_Inadequate dressing rooms or improper storage of personal items'),
 (0.0017516370516736707,
  'violation_description_Unauthorized or unsafe use of time as a public health control measure'),
 (0.0015229614848618564,
  'violation_description_Unclean unmaintained or improperly constructed toilet facilities'),
 (0.001277885489725238, 'violation_description_Other high risk violation'),
 (0.0012105545719455779, 'violation_description_Other low risk violation'),
 (0.0011033085661832666, 'months_num'),
 (0.0010908388990268987,
  'violation_description_Sewage or wastewater contamination'),
 (0.0010151044795228602,
  'violation_description_Improper food labeling or menu misrepresentation'),
 (0.0010062703869862116, 'neighborhoods'),
 (0.0009718069850019044, 'violation_description_Unapproved food source'),
 (0.0007510723042001787,
  'violation_description_Inadequate or unsanitary refuse containers or area or no garbage service'),
 (0.0006834219668601653, 'Current Police Districts'),
 (0.0006083566797014912, 'business_postal_code_1'),
 (0.0005338860923094405,
  'violation_description_Reservice of previously served foods'),
 (0.0005185612412311417, 'population'),
 (0.0005020385607509032, 'avg_income'),
 (0.0004320595125574816,
  'violation_description_Mobile food facility stored in unapproved location'),
 (0.0003248197943394919, 'violation_description_Unpermitted food facility'),
 (0.0003105406493750235,
  'violation_description_Noncompliance with Gulf Coast oyster regulation'),
 (0.0003082740338820756,
  'violation_description_Improper cooking time or temperatures'),
 (0.00030600384006154057,
  'violation_description_Mobile food facility not operating with an approved commissary'),
 (0.0002775742603078364,
  'violation_description_Consumer advisory not provided for raw or undercooked foods'),
 (0.00027121615630783404,
  'violation_description_No person in charge of food facility'),
 (0.0002456701281221526, 'violation_description_Worker safety hazards'),
 (0.0002384712353553616,
  'violation_description_Unsanitary employee garments hair or nails'),
 (0.00021606092728942267,
  'violation_description_Unapproved  living quarters in food facility'),
 (0.00018189006562169152, 'violation_description_Non service animal'),
 (9.697706065936737e-05,
  'violation_description_No plan review or Building Permit'),
 (3.8356080408735006e-05,
  'violation_description_Inadequate HACCP plan record keeping'),
 (1.026593947196598e-05,
  'violation_description_Improperly washed fruits and vegetables'),
 (0.0, 'violation_description_Discharge from employee nose mouth or eye')]

In [ ]:
# connect to database
# db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/movie_data"
# engine = create_engine(db_string)
# movies_df.to_sql(name='movies', con=engine, if_exists='replace')